# Generated by Django 5.0.4 on 2024-04-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
