# Generated by Django 5.0.4 on 2024-04-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
        migrations.AddField(
            model_name='photo',
            name='first_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='last_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='roll_number',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='student_class',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
