# Generated by Django 5.0.4 on 2024-04-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0005_remove_photo_name_photo_first_name_photo_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='roll_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='student_class',
            field=models.CharField(default='', max_length=100),
        ),
    ]
