# Generated by Django 5.0.4 on 2024-04-07 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0006_alter_photo_first_name_alter_photo_last_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='photo',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
