# Generated by Django 5.0.4 on 2024-04-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0007_remove_photo_first_name_remove_photo_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='student_class',
        ),
    ]
