# Generated by Django 5.0.4 on 2024-04-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0011_photo_color_studentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='color',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='Class',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], default='I', max_length=6),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='department',
            field=models.CharField(choices=[('AI/ML', 'AI/ML'), ('DS', 'DS'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')], default='CSE', max_length=6),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
    ]
