# Generated by Django 5.0.4 on 2024-04-08 03:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0012_remove_photo_color_studentdetails_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDetails',
            new_name='StudentDetail',
        ),
    ]
